name: Publish to GitHub Packages

permissions:
  contents: write
  packages: write

on:
  create:
    tags:
      - '*.*.*'

jobs:

  create-release:
    needs: [verify, publish]
    uses: ./.github/workflows/uu_create_release.yml
    secrets:
      UU_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

